language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install git+https://github.com/allegro/django-bob.git@develop
  - pip install . --use-mirrors
# command to run tests, e.g. python setup.py test
script: DJANGO_SETTINGS_MODULE=bob.tests.settings nosetests bob/tests/unit/dependencies.py
